theme: jekyll-theme-hacker
title: danXNU blog
description: This is my blog! Just some basic github pages with one of the default themes 

twitter_username: BraumPoro
github_username: danXNU

show_downloads: false
